[[redirects]]
  from = "/api"
  to = "https://send-email-1s1x.onrender.com/api"
  status = 201
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}